#!/usr/bin/env python3
"""Stamp line ranges onto whs-professional/references/INDEX.md rows.

INDEX.md maps keywords -> file -> section. This script appends (or refreshes)
a fourth column with the section's line range, so one grep of INDEX.md gives
an exact offset/limit for a targeted read instead of a whole-file load:

    noise | hazards.md | §14 | L909-992

Rows that point outside references/ (scripts, assets, examples) are left
alone. It also regenerates the "Section map" block at the foot of INDEX.md:
one row per section of every reference file (file | § | title | lines), so
files indexed only as "all" can still be read a section at a time.

Run after any edit that moves lines in a reference file.

Usage:
    python3 scripts/build_index.py           rewrite INDEX.md in place
    python3 scripts/build_index.py --check   exit 1 if INDEX.md is stale
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF_DIR = os.path.join(ROOT, "whs-professional", "references")
INDEX = os.path.join(REF_DIR, "INDEX.md")

NUMBERED = re.compile(r"^#{2,3}\s+(\d+)\.")
BOUNDARY = re.compile(r"^(#{2,3}\s+\d+\.|##\s)")
MAP_BEGIN = "## Section map (generated by scripts/build_index.py — do not edit by hand)"
MAP_NOTE = "Every section of every reference file. Format: `file | § | title | lines`."

_cache = {}


def sections(fn):
    """Return ({section number: (first line, last line)}, total lines)."""
    if fn not in _cache:
        with open(os.path.join(REF_DIR, fn), encoding="utf-8") as f:
            lines = f.read().split("\n")
        if lines and lines[-1] == "":
            lines.pop()
        starts = [i for i, l in enumerate(lines, 1) if BOUNDARY.match(l)]
        spans, rows = {}, []
        for k, start in enumerate(starts):
            end = starts[k + 1] - 1 if k + 1 < len(starts) else len(lines)
            while end > start and lines[end - 1].strip() in ("", "---"):
                end -= 1
            head = lines[start - 1]
            m = NUMBERED.match(head)
            title = re.sub(r"^#+\s+(\d+\.\s*)?", "", head).strip()
            if m:
                # company.md numbers its template and its worked example the
                # same way; the fuller occurrence is the one worth reading
                n, old = int(m.group(1)), spans.get(int(m.group(1)))
                if not old or end - start > old[1] - old[0]:
                    spans[n] = (start, end)
            if title.lower() != "table of contents":
                rows.append((m.group(1) if m else None, title, start, end))
        _cache[fn] = (spans, len(lines), rows)
    return _cache[fn][:2]


def section_map():
    """One row per section of every reference file (INDEX.md excluded)."""
    out = [MAP_BEGIN, MAP_NOTE]
    for fn in sorted(os.listdir(REF_DIR)):
        if not fn.endswith(".md") or fn == "INDEX.md":
            continue
        _, total = sections(fn)
        rows = _cache[fn][2]
        if not rows:
            out.append(f"{fn} | all | (whole file) | L1-{total}")
        for num, title, start, end in rows:
            out.append(f"{fn} | {'§' + num if num else '-'} | {title} | L{start}-{end}")
    return "\n".join(out)


def line_ranges(fn, spec):
    """Translate a section spec ('§4, §8', '§1-§7', 'all') to 'L..-..'."""
    spans, total = sections(fn)
    if spec.strip().lower() == "all":
        return f"L1-{total}"
    out = []
    for part in spec.split(","):
        nums = [int(n) for n in re.findall(r"§\s*(\d+)", part)]
        if not nums or any(n not in spans for n in nums):
            return None
        out.append(f"L{spans[nums[0]][0]}-{spans[nums[-1]][1]}")
    return ", ".join(out)


def rebuild(text):
    rows = []
    text = text.split(MAP_BEGIN)[0].rstrip("\n")
    for line in text.split("\n"):
        cells = [c.strip() for c in line.split(" | ")]
        if len(cells) in (3, 4) and cells[1].endswith(".md") and "/" not in cells[1]:
            fn = cells[1]
            if os.path.exists(os.path.join(REF_DIR, fn)):
                rng = line_ranges(fn, cells[2])
                if rng:
                    line = " | ".join(cells[:3] + [rng])
        rows.append(line)
    return "\n".join(rows) + "\n\n" + section_map() + "\n"


def main():
    with open(INDEX, encoding="utf-8") as f:
        current = f.read()
    fresh = rebuild(current)
    if "--check" in sys.argv[1:]:
        if fresh != current:
            print("INDEX.md line ranges are stale — run: python3 scripts/build_index.py")
            return 1
        return 0
    if fresh != current:
        with open(INDEX, "w", encoding="utf-8") as f:
            f.write(fresh)
        print("INDEX.md line ranges refreshed")
    else:
        print("INDEX.md already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
